#!/bin/bash

#NetPath
curl -o import/netpath.zip http://www.netpath.org/download/zipped/BioPAX.zip

#NCI Curated
curl -o import/NCI-Nature_Curated.bp3.owl.gz ftp://ftp1.nci.nih.gov/pub/PID/BioPAX_Level_3/NCI-Nature_Curated.bp3.owl.gz

#Reactome
curl -o import/reactome.zip http://www.reactome.org/download/current/biopax.zip

#BioCarta
curl -o import/BioCarta.bp3.owl.gz ftp://ftp1.nci.nih.gov/pub/PID/BioPAX_Level_3/BioCarta.bp3.owl.gz

#pathway commons
curl -o import/Pathway_Commons.homo_sapiens.BIOPAX.owl.gz http://www.pathwaycommons.org/pc2/downloads/Pathway%20Commons%202%20homo%20sapiens.BIOPAX.owl.gz

#use raptor from rapper to convert RDF to N3 triple format
#rapper -o ntriples Pathway_Commons.homo_sapiens.BIOPAX.owl > Pathway_Commons.homo_sapiens.BIOPAX.n3

cd import
mkdir -p owl

gunzip -c BioCarta.bp3.owl.gz > owl/BioCarta.bp3.owl
gunzip -c NCI-Nature_Curated.bp3.owl.gz > owl/NCI-Nature_Curated.bp3.owl
unzip netpath.zip 
mv BioPAX/* owl/
rmdir BioPAX
cd owl
unzip ../reactome.zip
cd ../../

# grep -n -P "[\x80-\xFF]" BioCarta.bp3.owl 